# Generated by Django 3.1.3 on 2020-11-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepCount_Data',
            fields=[
                ('saved_time', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('stepCount', models.IntegerField()),
            ],
            options={
                'db_table': 'stepcountData',
            },
        ),
    ]
